name: yay_thant
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.2.2
  http: ^1.2.1
  easy_localization: ^3.0.7
  fluttertoast: ^8.2.6
  fl_chart: ^0.69.0
  flutter_svg: ^2.0.10+1
  flutter_slidable: ^3.1.1
  file_picker: ^8.1.2
  cached_network_image: ^3.4.1
  calendar_date_picker2: ^1.1.5
  modal_bottom_sheet: ^3.0.0
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  package_info_plus: ^8.0.0
  latlong2: ^0.9.1
  geocoding: ^2.0.5
  internet_connection_checker_plus: ^2.7.0
  permission_handler: ^11.3.1
  device_info_plus: ^11.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Yay-d-3.png"

flutter:
  uses-material-design: true
  assets:
    - assets/languages/
    - assets/images/
    - assets/icons/
